version: '3.1'

services:
  php:
    image: php-dev
    build:
      context: ./docker
      args:
        PHP_VERSION: '${PHP_VERSION:-8.1}'
    ports:
      - '${PORT:-8000}:80'
    volumes:
      - './:/www'
    networks:
      - nw
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE:-database}'
      MYSQL_USER: '${DB_USERNAME:-username}'
      MYSQL_PASSWORD: '${DB_DATABASE:-password}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - nw

volumes:
  db:

networks:
  nw:
